language: ruby

dist: xenial
sudo: required

branches:
  only:
    - master

compiler:
  - gcc

rvm:
  - 2.2

before_install:
  - cd /home/travis/build/cropio/ruby-lwgeom
  - ./install-postgis-and-dependencies.sh
  - cd /home/travis/build/cropio/ruby-lwgeom

before_script:
  - gem build lwgeom.gemspec
  - gem install lwgeom

script:
  - rake test
